CREATE TABLE IF NOT EXISTS contract_details (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    contract_id           INTEGER NOT NULL UNIQUE REFERENCES contracts(id),
    policy_type           TEXT NOT NULL,
    product_name          TEXT,
    coverage_target       TEXT,
    auto_taininsho        TEXT,
    auto_taibutsusho      TEXT,
    auto_jinshin          TEXT,
    auto_toshasho         TEXT,
    auto_vehicle_amount   TEXT,
    auto_vehicle_type     TEXT,
    auto_deductible       TEXT,
    auto_nfl_grade        INTEGER,
    auto_age_condition    TEXT,
    auto_driver_limit     TEXT,
    auto_use_purpose      TEXT,
    auto_car_name         TEXT,
    auto_car_model        TEXT,
    auto_plate_no         TEXT,
    fire_building_amount  INTEGER,
    fire_household_amount INTEGER,
    fire_structure        TEXT,
    fire_location         TEXT,
    fire_quake_flg        INTEGER DEFAULT 0,
    fire_quake_amount     INTEGER,
    fire_flood_flg        INTEGER DEFAULT 0,
    fire_deductible       INTEGER,
    jibai_car_name        TEXT,
    jibai_car_model       TEXT,
    jibai_plate_no        TEXT,
    jibai_coverage_limit  TEXT,
    inj_death_amount      INTEGER,
    inj_disability_amount INTEGER,
    inj_hospital_daily    INTEGER,
    inj_surgery_benefit   TEXT,
    inj_outpatient_daily  INTEGER,
    inj_coverage_scope    TEXT,
    liab_coverage_limit   TEXT,
    liab_deductible       INTEGER,
    liab_jidan_flg        INTEGER DEFAULT 0,
    liab_coverage_scope   TEXT,
    cyber_3rd_limit       TEXT,
    cyber_leak_limit      TEXT,
    cyber_restore_limit   TEXT,
    cyber_biz_interruption_flg INTEGER DEFAULT 0,
    cyber_annual_revenue  TEXT,
    created_at            TEXT DEFAULT (datetime('now', 'localtime')),
    updated_at            TEXT DEFAULT (datetime('now', 'localtime'))
);
